### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by sineverba** [ilikenwf/nestedSortable#107]
I did open also on Stackoverflow.

But, I cannot get the array version.

This is the Fiddle:

https://jsfiddle.net/107bx70o/3/

And I did use also the last version.

Push the button, and you can see the error on console log.

Thank you very much.

**Comment by juanpscotto** [comment]
I have the same error.

**Comment by juanpscotto** [comment]
Hi, I figured out. Try to put your li items with an id like this:

```
<li class="dd-item" id="menuItem_1"></li>
<li class="dd-item" id="menuItem_2"></li>
<li class="dd-item" id="menuItem_3"></li>
.
.
.
```

That worked for me.
