### ISSUE TITLE
Allow Drag-Drop from one nestedSortable tree to another

### ISSUE THREAD

**Issue by MichaelSamteladze** [ilikenwf/nestedSortable#121]
It would be great, if I have two nestedSortable trees on a page, I could move tree items from one tree to another.

**Comment by ovalek** [comment]
This is possible. Use `connectWith` option the same way as in original jQuery UI Sortable component. https://jqueryui.com/sortable/#connect-lists

**Comment by MichaelSamteladze** [comment]
Thanks for reply, it worked, i was using v1.x and when I switched to v2.x all worked fine.

Thanks
