### ISSUE TITLE
NestedSortable requires method $.ui.isOverAxis() which is deprecated since  jQuery UI 1.10

### ISSUE THREAD

**Issue by mind2machine** [ilikenwf/nestedSortable#78]
After upgrading to JQuery UI 1.10 in order to solve some other bugs in my application, nested sortable stopped working, raising the following javascript error :
Uncaught TypeError: $.ui.isOverAxis is not a function in jquery.mjs.nestedSortable.js at line 315 

After some search, I found out the function has been removed since jQuery UI 1.10 :+1: 

> The $.ui.isOver() and $.ui.isOverAxis() methods were written for specific plugins and had less-than-obvious APIs. They have been deprecated for a while, and as such have been removed.

**Quick and simple fix : **
1) Replicate this fairly simple function inside the NestedSortable source code : 

> 	isOverAxis: function( x, reference, size ) {
		//Determines when x coordinate is over "b" element axis
		return ( x > reference ) && ( x < ( reference + size ) );
	},

2) Then, at line 315 of jquery.mjs.nestedSortable.js we simply have to replace 3 calls to $.ui.isOverAxis() by this.isOverAxis() :

> var isOverBottomHalf = this.isOverAxis(this.positionAbs.top + this.offset.click.top, item.top + (item.height*half), item.height),
				isOverTopHalf = this.isOverAxis(this.positionAbs.top + this.offset.click.top, item.top - (item.height*half), item.height),
				isOverRightHalf = this.isOverAxis(this.positionAbs.left + this.offset.click.left, item.left + (item.width/2), item.width),
				verticalDirection = this._getDragVerticalDirection(),
				horizontalDirection = this._getDragHorizontalDirection()

**Comment by ilikenwf** [comment]
Can you make a pull request and submit it with the changes required, please?

**Comment by AlexHill** [comment]
This was fixed nearly three years ago, in 1c8b7204d153dd930676bdb8ffdcc2e4f7a05ac9.

**Comment by mind2machine** [comment]
This is weird. I was running nestedSortable 2.0 though. I guess I have downloaded the outdated version from [this page](https://github.com/mjsarfatti/nestedSortable) instead of the one of the new repository. 

Maybe that outdated file should be replaced / retired then. Also incrementing the version number to 2 dot something instead of 2.0 alpha (since 3 years) would drive people to choose the correct version. My 2 cents ... ;-)

Thanks for the quick feedback by the way. I am going to update to the latest version from github.

Regards

**Comment by AlexHill** [comment]
Totally agree that the versioning is confusing. I'm not a contributor to this project, I just came across this ticket today when I ran into the same problem. I was going to just patch my old version to fix this problem but decided to upgrade to the latest. When I went to patch that, I noticed it had already been done.

**Comment by ilikenwf** [comment]
You can be a contributor if you even submit a new version number :)

I can tag it after the fact, I have trouble remembering to do things like
this as I manage several projects in various places on top of my day job.

**Comment by AlexHill** [comment]
Hey, didn't mean to sound at all complainey. Thanks for your hard work!

**Comment by ilikenwf** [comment]
What hard work? :)
