### ISSUE TITLE
update tags to the latest version

### ISSUE THREAD

**Issue by maruilian11** [ilikenwf/nestedSortable#84]
hi, we host you lib on https://cdnjs.com, because we use **git auto-update config** depending on git tags, could you please update tags between 1.3.4 and the latest version, and we can keep every released version on cdnjs.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/7337#issuecomment-202116411

**Comment by ilikenwf** [comment]
The tags you see are the only officially released versions. Any bumps in between are irrelevant as 2.0 and the 1.x tags are the only ones people ever have used in production, or at least should be.
